import { Input, Component } from '@angular/core';
import { FormGroup } from '@angular/forms';

@Component({
  template: '',
})
export class BaseDetailComponent<Type, Lookups> {
  displayStrings: any = {};

  @Input()
  lookups: Lookups;
  protected _item: Type;
  public get item(): Type {
    return this._item;
  }
  @Input()
  public set item(v: Type) {
    this._item = v;
  }

  private _readOnly: boolean;

  public get readOnly(): boolean {
    return this._readOnly;
  }
  @Input()
  public set readOnly(v: boolean) {
    this._readOnly = v;
  }
  @Input()
  hasAutoGeneratedKey = false;
  @Input()
  editForm: FormGroup;
}
