/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.0.6.0 (NJsonSchema v10.0.23.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { Injector } from '@angular/core';
import {
  mergeMap as _observableMergeMap,
  catchError as _observableCatch,
} from 'rxjs/operators';
import {
  Observable,
  throwError as _observableThrow,
  of as _observableOf,
} from 'rxjs';
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { AbpEnum } from '@abpdz/ng.core';

@Injectable({
  providedIn: 'root',
})
export class AbpEnumServiceProxy {
  path = '/api/app/abp-enum/';
  delete(id: number): any {
    return this.http.delete(this.path + id);
  }
  createOrUpdate(arg0: any): any {
    var data = { ...arg0 };
    if (data.id) {
      //delete data.id;
    }
    return arg0.id
      ? this.http.put(this.path + 'rest-update', data)
      : this.http.post(this.path, data);
  }
  import(arg0: any): any {
    return this.http.post(this.path + 'import', arg0);
  }
  constructor(public http: HttpClient) {}

  /**
   * @return Success
   */
  getAll(): Observable<AbpEnum[]> {
    return this.http.get<AbpEnum[]>(this.path + 'all');
  }
}
